baseURL = 'https://www.justagenesis.com/'
languageCode = 'en-us'
title = 'Its just a Genesis!'
theme = 'ananke'

[deployment]
[[deployment.targets]]

name = "production"
URL = "s3://www.justagenesis.com?region=us-east-2"